### ISSUE TITLE
arc data services - connection brake to arc controller

### ISSUE THREAD

**Issue by katomel4** [microsoft/azure_arc#471]
arc data services on aks 1.18
works fine and after awhile there is no connection to the arc controller. happens on both of my aks clusters:

azdata_command_data_logger : command args: login --username arcadmin --accept-eula y --namespace arc --debug
2021-03-24 17:59:53.0464 UTC | DEBUG | metadata file logging enabled - writing logs to "C:\Users\omery\.azdata\commands".
2021-03-24 17:59:53.0466 UTC | DEBUG | Event: CommandInvoker.OnPreCommandTableCreate []
2021-03-24 17:59:53.0469 UTC | DEBUG | Event: CommandLoader.OnLoadArguments []
2021-03-24 17:59:53.0473 UTC | DEBUG | Event: CommandInvoker.OnPostCommandTableCreate []
2021-03-24 17:59:53.0795 UTC | DEBUG | Event: CommandInvoker.OnCommandTableLoaded []
2021-03-24 17:59:53.0803 UTC | DEBUG | Event: CommandInvoker.OnPreParseArgs []
2021-03-24 17:59:53.0806 UTC | DEBUG | Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x041AA858>, <function CLIQuery.handle_query_parameter at 0x041C0978>]
2021-03-24 17:59:53.0808 UTC | DEBUG | Controller endpoint https://20.71.68.147:30080
2021-03-24 17:59:53.0811 UTC | DEBUG | Attached optional services None
2021-03-24 17:59:53.0812 UTC | DEBUG | ['BILLING_MODEL_COMSUMPTION', 'CLUSTER_CONNECTION_MODE_DISCONNECTED', 'CUSTOM_OBJECT_NAME', 'DEFAULT_DATA_CONTROLLER_NAME', 'GUID_REGEX', 'INSTANCE_NAME', 'INSTANCE_TYPE', 'INSTANCE_TYPE_DATA_CONTROLLER', 'LOCATION', 'RESOURCE_GROUP_NAME', 'SUBSCRIPTION_ID', '__abstractmethods__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_abc_cache', '_abc_negative_cache', '_abc_negative_cache_version', '_abc_registry', 'acquire_token', 'api_client', 'create_app', 'create_cluster', 'create_mount', 'delete_app', 'delete_cluster', 'delete_instance', 'delete_mount', 'delete_registration_instance', 'endpoint', 'get_bdc_status', 'get_cluster', 'get_cluster_state', 'get_control_status', 'get_controller_logs', 'get_endpoints', 'get_instance', 'get_mount_status', 'get_version_info', 'is_ready', 'list_app', 'list_apps', 'list_deleted_resources', 'list_registration_instances', 'logs_post', 'metrics_post', 'refresh_mount', 'register_instance', 'register_instance_by_configuration', 'resource_crd_get', 'resource_spec_get', 'resource_types_get', 'set_authorization_header', 'signing_certificate_public_key_get', 'update_app', 'upgrade_bdc', 'upgrade_control_plane', 'usage_calculate_post', 'usages_post']
urllib3.connectionpool : Starting new HTTPS connection (1): aks2-dns-6b806726.hcp.westeurope.azmk8s.io:443
urllib3.connectionpool : https://aks2-dns-6b806726.hcp.westeurope.azmk8s.io:443 "GET /api/v1/namespaces/arc/services/controller-svc-external HTTP/1.1" 200 1893
kubernetes.client.rest : response body: {"kind":"Service","apiVersion":"v1","metadata":{"name":"controller-svc-external","namespace":"arc","selfLink":"/api/v1/namespaces/arc/services/controller-svc-external","uid":"26d8ad2b-2203-4961-a1a0-6ef9e33a8714","resourceVersion":"31794","creationTimestamp":"2021-03-21T19:30:05Z","labels":{"MSSQL_NAMESPACE":"arc","app":"controller","plane":"control","role":"controller"},"ownerReferences":[{"apiVersion":"v1alpha1","kind":"datacontroller","name":"arc-dc","uid":"169cb926-e61b-496f-aa47-b68dbbcb05cf"}],"finalizers":["service.kubernetes.io/load-balancer-cleanup"],"managedFields":[{"manager":"bootstrapper","operation":"Update","apiVersion":"v1","time":"2021-03-21T19:30:05Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{".":{},"f:MSSQL_NAMESPACE":{},"f:app":{},"f:plane":{},"f:role":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"169cb926-e61b-496f-aa47-b68dbbcb05cf\"}":{".":{},"f:apiVersion":{},"f:kind":{},"f:name":{},"f:uid":{}}}},"f:spec":{"f:externalTrafficPolicy":{},"f:ports":{".":{},"k:{\"port\":30080,\"protocol\":\"TCP\"}":{".":{},"f:name":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{".":{},"f:MSSQL_NAMESPACE":{},"f:app":{},"f:plane":{},"f:role":{}},"f:sessionAffinity":{},"f:type":{}}}},{"manager":"kube-controller-manager","operation":"Update","apiVersion":"v1","time":"2021-03-21T19:30:10Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:finalizers":{".":{},"v:\"service.kubernetes.io/load-balancer-cleanup\"":{}}},"f:status":{"f:loadBalancer":{"f:ingress":{}}}}}]},"spec":{"ports":[{"name":"port-1","protocol":"TCP","port":30080,"targetPort":8443,"nodePort":30015}],"selector":{"MSSQL_NAMESPACE":"arc","app":"controller","plane":"control","role":"controller"},"clusterIP":"10.0.244.89","type":"LoadBalancer","sessionAffinity":"None","externalTrafficPolicy":"Cluster"},"status":{"loadBalancer":{"ingress":[{"ip":"51.138.29.57"}]}}}

Password:
2021-03-24 18:00:04.0704 UTC | DEBUG | request url: https://51.138.29.57:30080/api/v1/token
2021-03-24 18:00:04.0705 UTC | DEBUG | request method: POST
2021-03-24 18:00:04.0707 UTC | DEBUG | request header[Accept]: application/json
2021-03-24 18:00:04.0707 UTC | DEBUG | request header[version]: 15.0.4100
2021-03-24 18:00:04.0709 UTC | DEBUG | request header[User-Agent]: azdata-cli-core/20.3.1/python
2021-03-24 18:00:04.0711 UTC | DEBUG | request header[Authorization]: <PRIVATE>
2021-03-24 18:00:04.0714 UTC | DEBUG | request header[Content-Type]: application/json
2021-03-24 18:00:04.0717 UTC | DEBUG | request payload: None
urllib3.connectionpool : Starting new HTTPS connection (1): 51.138.29.57:30080
urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x084C45D0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)': /api/v1/token
urllib3.connectionpool : Starting new HTTPS connection (2): 51.138.29.57:30080
urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x084C4A50>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)': /api/v1/token
urllib3.connectionpool : Starting new HTTPS connection (3): 51.138.29.57:30080
urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x084C4690>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)': /api/v1/token
urllib3.connectionpool : Starting new HTTPS connection (4): 51.138.29.57:30080

**Comment by katomel4** [comment]
2021-03-24 18:01:28.0914 UTC | ERROR | Cannot connect with endpoint. Verify that you defined the endpoint correctly by running "azdata login --endpoint <endpoint>" again. Also verify that the endpoint is reachable.
(60)
Reason: MaxRetryError
HTTPSConnectionPool(host='51.138.29.57', port=30080): Max retries exceeded with url: /api/v1/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection 
object at 0x084ABEF0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period 
of time, or established connection failed because connected host has failed to respond',))

Traceback (most recent call last):

  File "D:\a\1\s\projects\cli\output\msi\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 159, in _new_conn

  File "D:\a\1\s\projects\cli\output\msi\artifacts\cli\Lib\site-packages\urllib3/util/connection.py", line 80, in create_connection

  File "D:\a\1\s\projects\cli\output\msi\artifacts\cli\Lib\site-packages\urllib3/util/connection.py", line 70, in create_connection

TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "D:\a\1\s\projects\cli\output\msi\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 600, in urlopen

  File "D:\a\1\s\projects\cli\output\msi\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 343, in _make_request

  File "D:\a\1\s\projects\cli\output\msi\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 839, in _validate_conn

  File "D:\a\1\s\projects\cli\output\msi\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 301, in connect

  File "D:\a\1\s\projects\cli\output\msi\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 168, in _new_conn

urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x084ABEF0>: Failed to establish a new connection: [WinError 10060] A connection 
attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond     


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "D:\a\1\s\projects\cli\output\msi\artifacts\cli\Lib\site-packages\azdata/cli/core/clients/api_client.py", line 883, in request

  File "D:\a\1\s\projects\cli\output\msi\artifacts\cli\Lib\site-packages\urllib3/request.py", line 72, in request

  File "D:\a\1\s\projects\cli\output\msi\artifacts\cli\Lib\site-packages\urllib3/request.py", line 150, in request_encode_body

  File "D:\a\1\s\projects\cli\output\msi\artifacts\cli\Lib\site-packages\urllib3/poolmanager.py", line 324, in urlopen

  File "D:\a\1\s\projects\cli\output\msi\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 667, in urlopen

  File "D:\a\1\s\projects\cli\output\msi\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 667, in urlopen

  File "D:\a\1\s\projects\cli\output\msi\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 667, in urlopen

  File "D:\a\1\s\projects\cli\output\msi\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 638, in urlopen

  File "D:\a\1\s\projects\cli\output\msi\artifacts\cli\Lib\site-packages\urllib3/util/retry.py", line 399, in increment

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='51.138.29.57', port=30080): Max retries exceeded with url: /api/v1/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x084ABEF0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "D:\a\1\s\projects\cli\output\msi\artifacts\cli\Lib\site-packages\azdata/cli/core/profile.py", line 646, in authenticate

  File "D:\a\1\s\projects\cli\output\msi\artifacts\cli\Lib\site-packages\azdata/cli/core/clients/controller_client.py", line 279, in acquire_token

  File "D:\a\1\s\projects\cli\output\msi\artifacts\cli\Lib\site-packages\azdata/cli/core/api/token_router_api.py", line 53, in token_post

  File "D:\a\1\s\projects\cli\output\msi\artifacts\cli\Lib\site-packages\azdata/cli/core/api/token_router_api.py", line 119, in token_post_with_http_info

  File "D:\a\1\s\projects\cli\output\msi\artifacts\cli\Lib\site-packages\azdata/cli/core/clients/api_client.py", line 362, in call_api

  File "D:\a\1\s\projects\cli\output\msi\artifacts\cli\Lib\site-packages\azdata/cli/core/clients/api_client.py", line 189, in __call_api

  File "D:\a\1\s\projects\cli\output\msi\artifacts\cli\Lib\site-packages\azdata/cli/core/clients/api_client.py", line 401, in request

  File "D:\a\1\s\projects\cli\output\msi\artifacts\cli\Lib\site-packages\azdata/cli/core/clients/api_client.py", line 1019, in POST

  File "D:\a\1\s\projects\cli\output\msi\artifacts\cli\Lib\site-packages\azdata/cli/core/clients/api_client.py", line 942, in request

azdata.cli.core.exceptions.ApiError: (60)
Reason: MaxRetryError
HTTPSConnectionPool(host='51.138.29.57', port=30080): Max retries exceeded with url: /api/v1/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection 
object at 0x084ABEF0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period 
of time, or established connection failed because connected host has failed to respond',))



During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "D:\a\1\s\projects\cli\output\msi\artifacts\cli\Lib\site-packages\azdata/cli/commands/profile/custom.py", line 109, in login

  File "D:\a\1\s\projects\cli\output\msi\artifacts\cli\Lib\site-packages\azdata/cli/commands/profile/client.py", line 50, in login

  File "D:\a\1\s\projects\cli\output\msi\artifacts\cli\Lib\site-packages\azdata/cli/core/profile.py", line 650, in authenticate

azdata.cli.core.exceptions.ApiError: (60)
Reason: MaxRetryError
HTTPSConnectionPool(host='51.138.29.57', port=30080): Max retries exceeded with url: /api/v1/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection 
object at 0x084ABEF0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period 
of time, or established connection failed because connected host has failed to respond',))


2021-03-24 18:01:28.0989 UTC | ERROR | Cannot connect with endpoint. Verify that you defined the endpoint correctly by running "azdata login --endpoint <endpoint>" again. Also verify that the endpoint is reachable.
(60)
Reason: MaxRetryError
HTTPSConnectionPool(host='51.138.29.57', port=30080): Max retries exceeded with url: /api/v1/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection 
object at 0x084ABEF0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period 
of time, or established connection failed because connected host has failed to respond',))
